<a href="https://colab.research.google.com/github/takky0330/wisper/blob/main/wisper_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install pyannote-audio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 5.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 898.7/898.7 kB 54.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.0/811.0 kB 57.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.3/119.3 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.2/807.2 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 10.6 MB/s eta 0:00:0

In [1]:
import numpy as np
from pyannote.audio import Pipeline, Audio
from pyannote.core import Segment
from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding

In [2]:
!pip install moviepy

In [3]:
from moviepy.editor import VideoFileClip

In [5]:
video_path = "./9d4fc932d442ef2ffb17d0a8086390e6_1725887318814_0.mp4"
video_path = "./Sample_data_Hisajima-Mitsumura.mp4"
audio_path = '.'.join(video_path.split('.')[:-1]) + '.wav'
video = VideoFileClip(video_path)
video.audio.write_audiofile(audio_path, ffmpeg_params=["-ac", "1"])  #モノラルで出力

MoviePy - Writing audio in ./Sample_data_Hisajima-Mitsumura.wav


MoviePy - Done.


In [6]:
!pip install git+https://github.com/openai/whisper.git

  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-71vl7wtt
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-71vl7wtt
  Resolved https://github.com/openai/whisper.git to commit 279133e3107392276dc509148da1f41bfb532c7e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.4/209.4 MB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 61.7 MB/s eta 0:00:00
  Created wheel for openai-whisper: filename=openai_whisper-20231117-py3-none-any.whl size=802819 sha256=9350fb4b760149ae1c84cda7fecfc961e2010480eebc461b7287c5f448541af5
  Stored in directory: /tmp/pip-ephem-wheel-cache-v5uv_hzf/wheels/8b/6c/d0/622666868c179f156cf595c8b6f06f88bc5d80c4b31dccaa03
Successfully built openai-whisper


In [7]:
import whisper
import json, re

In [8]:
model = whisper.load_model("large", device="cpu")
_ = model.cuda()

100%|██████████████████████████████████████| 2.88G/2.88G [00:25<00:00, 123MiB/s]


In [38]:
result = model.transcribe(audio_path, verbose=True, fp16=False, language="ja", word_timestamps=True)

[00:00.000 --> 00:05.780] 今日はですね、物を買われたりサービスを使われた時に
[00:06.620 --> 00:13.180] どういうことを思っていらっしゃるとか、そういう関連のことをお伺いしたいと思って来ていただきました。
[00:13.800 --> 00:19.560] ちょっといろいろとお話を伺って、今後のサービスとかいろいろ考えるときに
[00:19.560 --> 00:26.200] 会社だと思っていますので、ゆるい感じでお話を伺えればと思いますので、よろしくお願いします。
[00:26.200 --> 00:26.820] はい、お願いします。
[00:27.560 --> 00:38.760] あと一応今回のインタビューなんですけど、録音とか録画とかをさせていただいているんですけれども
[00:39.600 --> 00:47.560] 関係者だけ見るだけで、特に他に渡しませんので、あとは個人情報等々もしっかり守らせていただきますので、ご安心ください。
[00:47.900 --> 00:48.280] はい。
[00:48.520 --> 00:49.760] じゃあよろしくお願いします。
[00:50.400 --> 00:50.580] はい。
[00:53.000 --> 00:56.060] まず簡単にいいんですけど、お名前とかお仕事とか、
[00:56.200 --> 00:56.320] はい。
[00:56.860 --> 01:02.620] ご家族とか、あと最近の趣味とか、最近の趣味っておかしいですね。
[01:02.760 --> 01:07.140] 趣味とか、最近こんなこと気になっているとか、こういうことやっているみたいなことがあれば、
[01:07.700 --> 01:10.320] 自己紹介みたいな感じでちょっと教えてもらってもいいですか。
[01:10.500 --> 01:10.760] はい。
[01:10.960 --> 01:11.080] はい。
[01:14.120 --> 01:15.440] 三村と言います。
[01:15.600 --> 01:15.840] はい。
[01:15.880 --> 01:16.160] はい。
[01:19.160 --> 01:19.

In [39]:
result

{'text': '今日はですね、物を買われたりサービスを使われた時にどういうことを思っていらっしゃるとか、そういう関連のことをお伺いしたいと思って来ていただきました。ちょっといろいろとお話を伺って、今後のサービスとかいろいろ考えるときに会社だと思っていますので、ゆるい感じでお話を伺えればと思いますので、よろしくお願いします。はい、お願いします。あと一応今回のインタビューなんですけど、録音とか録画とかをさせていただいているんですけれども関係者だけ見るだけで、特に他に渡しませんので、あとは個人情報等々もしっかり守らせていただきますので、ご安心ください。はい。じゃあよろしくお願いします。はい。まず簡単にいいんですけど、お名前とかお仕事とか、はい。ご家族とか、あと最近の趣味とか、最近の趣味っておかしいですね。趣味とか、最近こんなこと気になっているとか、こういうことやっているみたいなことがあれば、自己紹介みたいな感じでちょっと教えてもらってもいいですか。はい。はい。三村と言います。はい。はい。仕事は、三村さん、なんて呼ばれているんですか、お友達には。あだ名と言います。あだ名は、結構名前を文字って呼ばれるかと思って。はい。なんか名前で呼び捨てされたり、なんかバリエーションいろいろあるんですけど、あります。こんな感じなんですね。はい。そんな感じです。はい。で、引き継ぎ。はい。仕事は、会社でデスクワークをしています。はい。はい。で、趣味は、美術館に行ったりとか、舞台を見に行ったりとか、コンサート行って、音楽聴きに行ったりとかするのが好きなので、かなりよく行っていると思います。あと何でしたっけ。大体ご家族とか親御さんと住んでいらっしゃるとか。そうですね。今は実家にいるので、両親と、3人で住んでいます。なるほど。はい。3人で住んでいる。はい。あれですか。趣味の美術とか音楽とかっていうのは、はい。どれぐらい、なんかよく行かれるってことなんですけど、どこに行ったりとか。美術で行くと、なんか美術館だったりとか、なんかもうちょっと小っちゃい個展みたいなのだったり、いろいろなんですけど、土日はどっちかは行きたいなっていう。そうなんですか。感じなので、多分週1回以上は行ってると思います。へぇ。あとは、そういうのが好きな友達と一緒にいると、なんかはしごしたりするので。はい。',
 'segment

In [101]:
segments = result['segments']
prog = re.compile('教えて|聞か|聞き|願い|ください|ですか|でしょうか|ましたか|されましたか|いつ頃')
INTERVIEW = []
for seg in segments:
  count = len(prog.findall(seg['text']))
  if count > 0: print(str(seg['id']) + " : " + seg['text'])
  _seg = {'start': round(seg['start'], 2), 'end': round(seg['end'], 2), 'text': seg['text'], 'count': count}
  INTERVIEW.append(_seg)

3 : 会社だと思っていますので、ゆるい感じでお話を伺えればと思いますので、よろしくお願いします。
4 : はい、お願いします。
6 : 関係者だけ見るだけで、特に他に渡しませんので、あとは個人情報等々もしっかり守らせていただきますので、ご安心ください。
8 : じゃあよろしくお願いします。
14 : 自己紹介みたいな感じでちょっと教えてもらってもいいですか。
21 : 三村さん、なんて呼ばれているんですか、お友達には。
48 : あれですか。
53 : そうなんですか。


In [82]:
segments = result['segments']
embedding_model = PretrainedSpeakerEmbedding("speechbrain/spkrec-ecapa-voxceleb", device='cpu')
embeddings = np.zeros(shape=(len(segments), 192))

duration = video.duration
embeddings = []


for i, segment in enumerate(segments):
    audio = Audio()
    start = round(segment["start"], 2)
    end = round(min(duration, segment["end"]), 2)
    clip = Segment(start, end)
    waveform, sample_rate = audio.crop(audio_path, clip)
    print(waveform[0])
    _enbed = embedding_model(waveform[None])
    #print(_enbed[0])
    embeddings.append(_enbed[0])

embeddings = np.nan_to_num(embeddings)


tensor([0.0000, 0.0000, 0.0000,  ..., 0.0238, 0.0236, 0.0207])
tensor([-0.0168, -0.0165, -0.0150,  ..., -0.0024, -0.0023, -0.0026])
tensor([-1.3123e-03, -1.3428e-03, -2.4414e-04,  ..., -6.1035e-05,
        -2.2583e-03, -4.5776e-03])
tensor([-6.3477e-03, -7.8430e-03, -7.5684e-03,  ..., -3.7231e-03,
        -2.5635e-03,  3.0518e-05])
tensor([ 0.0007, -0.0013, -0.0022,  ...,  0.0014,  0.0045,  0.0020])
tensor([ 0.0173,  0.0176,  0.0172,  ..., -0.0032, -0.0033, -0.0028])
tensor([-0.0136, -0.0121, -0.0116,  ..., -0.0063, -0.0049, -0.0047])
tensor([0.0033, 0.0026, 0.0021,  ..., 0.0035, 0.0037, 0.0038])
tensor([ 0.0029,  0.0022,  0.0041,  ..., -0.0062, -0.0064, -0.0083])
tensor([-0.0028, -0.0025, -0.0034,  ..., -0.0016, -0.0009, -0.0018])
tensor([-0.0022, -0.0020, -0.0019,  ..., -0.0015, -0.0020, -0.0008])
tensor([0.0103, 0.0103, 0.0120,  ..., 0.0041, 0.0059, 0.0048])
tensor([0.0003, 0.0006, 0.0006,  ..., 0.0119, 0.0118, 0.0091])
tensor([ 0.0033,  0.0042,  0.0045,  ..., -0.0686, -0.0703, -0.0

In [83]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
speaker_count = 2

In [84]:
embeddings.shape

(58, 192)

In [112]:
clustering_agg = AgglomerativeClustering(speaker_count).fit(embeddings)

In [113]:
clustering_kmeans = KMeans(n_clusters=speaker_count).fit(embeddings)

In [116]:
#clustering = clustering_agg
clustering = clustering_kmeans

speek = [0] * speaker_count
for s, (speaker, _, text) in enumerate(labeled_segments):
    speek[speaker] += INTERVIEW[s]["count"]
inteviewer_index = np.argmax(speek)

labeled_segments = []
for label, segment in zip(clustering.labels_, result["segments"]):
    labeled_segments.append((label, segment["start"], segment["text"]))

interivew = []
print(INTERVIEW)
for s, (speaker, _, text) in enumerate(labeled_segments):
    stime = INTERVIEW[s]["start"]
    SPEAKER = 'モニタ　　　　'
    if speaker == inteviewer_index:
      SPEAKER = 'インタビューア'
    interivew.append(f"{SPEAKER} :  {stime} 〜 : 「{text}」")

[{'start': 0.0, 'end': 5.78, 'text': '今日はですね、物を買われたりサービスを使われた時に', 'count': 0}, {'start': 6.62, 'end': 13.18, 'text': 'どういうことを思っていらっしゃるとか、そういう関連のことをお伺いしたいと思って来ていただきました。', 'count': 0}, {'start': 13.8, 'end': 19.56, 'text': 'ちょっといろいろとお話を伺って、今後のサービスとかいろいろ考えるときに', 'count': 0}, {'start': 19.56, 'end': 26.2, 'text': '会社だと思っていますので、ゆるい感じでお話を伺えればと思いますので、よろしくお願いします。', 'count': 1}, {'start': 26.2, 'end': 26.82, 'text': 'はい、お願いします。', 'count': 1}, {'start': 27.56, 'end': 38.76, 'text': 'あと一応今回のインタビューなんですけど、録音とか録画とかをさせていただいているんですけれども', 'count': 0}, {'start': 39.6, 'end': 47.56, 'text': '関係者だけ見るだけで、特に他に渡しませんので、あとは個人情報等々もしっかり守らせていただきますので、ご安心ください。', 'count': 1}, {'start': 47.9, 'end': 48.28, 'text': 'はい。', 'count': 0}, {'start': 48.52, 'end': 49.76, 'text': 'じゃあよろしくお願いします。', 'count': 1}, {'start': 50.4, 'end': 50.58, 'text': 'はい。', 'count': 0}, {'start': 53.0, 'end': 56.06, 'text': 'まず簡単にいいんですけど、お名前とかお仕事とか、', 'count': 0}, {'start': 56.2, 'end': 56.32, 'text': 'はい。', 'count': 0}, {'start': 56.86, 'end': 

In [117]:
for speek in interivew:
  print(speek)

モニタ　　　　 :  0.0 〜 : 「今日はですね、物を買われたりサービスを使われた時に」
モニタ　　　　 :  6.62 〜 : 「どういうことを思っていらっしゃるとか、そういう関連のことをお伺いしたいと思って来ていただきました。」
モニタ　　　　 :  13.8 〜 : 「ちょっといろいろとお話を伺って、今後のサービスとかいろいろ考えるときに」
モニタ　　　　 :  19.56 〜 : 「会社だと思っていますので、ゆるい感じでお話を伺えればと思いますので、よろしくお願いします。」
インタビューア :  26.2 〜 : 「はい、お願いします。」
モニタ　　　　 :  27.56 〜 : 「あと一応今回のインタビューなんですけど、録音とか録画とかをさせていただいているんですけれども」
モニタ　　　　 :  39.6 〜 : 「関係者だけ見るだけで、特に他に渡しませんので、あとは個人情報等々もしっかり守らせていただきますので、ご安心ください。」
インタビューア :  47.9 〜 : 「はい。」
モニタ　　　　 :  48.52 〜 : 「じゃあよろしくお願いします。」
インタビューア :  50.4 〜 : 「はい。」
モニタ　　　　 :  53.0 〜 : 「まず簡単にいいんですけど、お名前とかお仕事とか、」
インタビューア :  56.2 〜 : 「はい。」
モニタ　　　　 :  56.86 〜 : 「ご家族とか、あと最近の趣味とか、最近の趣味っておかしいですね。」
モニタ　　　　 :  62.76 〜 : 「趣味とか、最近こんなこと気になっているとか、こういうことやっているみたいなことがあれば、」
モニタ　　　　 :  67.7 〜 : 「自己紹介みたいな感じでちょっと教えてもらってもいいですか。」
インタビューア :  70.5 〜 : 「はい。」
インタビューア :  70.96 〜 : 「はい。」
モニタ　　　　 :  74.12 〜 : 「三村と言います。」
インタビューア :  75.6 〜 : 「はい。」
インタビューア :  75.88 〜 : 「はい。」
モニタ　　　　 :  79.16 〜 : 「仕事は、」
モニタ　　　　 :  80.0 〜 : 「三村さん、なんて呼ばれているんですか、お友達には。」
インタビューア :  85.5 〜 