<a href="https://colab.research.google.com/github/takky0330/wisper/blob/main/wisper_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyannote-audio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 8.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 898.7/898.7 kB 40.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.0/811.0 kB 40.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.3/119.3 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.2/807.2 kB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 7.8 MB/s eta 0:00:00


In [1]:
import numpy as np
from pyannote.audio import Pipeline, Audio
from pyannote.core import Segment
from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding

In [2]:
!pip install moviepy

In [3]:
from moviepy.editor import VideoFileClip

In [4]:
video_path = "./9d4fc932d442ef2ffb17d0a8086390e6_1725887318814_0.mp4"
video_path = "./Sample_data_Hisajima-Mitsumura.mp4"
audio_path = '.'.join(video_path.split('.')[:-1]) + '.wav'
video = VideoFileClip(video_path)
video.audio.write_audiofile(audio_path, ffmpeg_params=["-ac", "1"])  #モノラルで出力

MoviePy - Writing audio in ./Sample_data_Hisajima-Mitsumura.wav


MoviePy - Done.


In [5]:
!pip install git+https://github.com/openai/whisper.git

  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-crxa6h__
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-crxa6h__
  Resolved https://github.com/openai/whisper.git to commit 279133e3107392276dc509148da1f41bfb532c7e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.4/209.4 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 48.0 MB/s eta 0:00:00
  Created wheel for openai-whisper: filename=openai_whisper-20231117-py3-none-any.whl size=802819 sha256=2b8f6f6eeb561b6609bfef99bac4957bcfc9e53602560571118603b1b7b45b18
  Stored in directory: /tmp/pip-ephem-wheel-cache-hdcg5f9a/wheels/8b/6c/d0/622666868c179f156cf595c8b6f06f88bc5d80c4b31dccaa03
Successfully built openai-whisper


In [6]:
import whisper
import json, re

In [ ]:
model = whisper.load_model("large")

100%|█████████████████████████████████████| 2.88G/2.88G [00:54<00:00, 56.6MiB/s]


In [17]:
result = model.transcribe(audio_path, verbose=True, fp16=False, language="ja")

[00:00.000 --> 00:06.000] 今日はですね、ものを買われたり、サービスとか使われる時に、
[00:06.000 --> 00:09.000] どういうことを思っていらっしゃるとか、
[00:09.000 --> 00:12.000] そういう関係のことをお伺いしたいと思って、
[00:12.000 --> 00:14.000] 来ていただきました。
[00:14.000 --> 00:18.000] いろいろとお話を伺って、今後のサービスとか、
[00:18.000 --> 00:22.000] いろいろ考える時に、いかしてもらおうと思っておりますので、
[00:22.000 --> 00:25.000] 緩い感じでお話を伺えるようだと思いますので、
[00:25.000 --> 00:27.000] よろしくお願いします。
[00:27.000 --> 00:31.000] はい。あと一応今回のインタビューなんですけど、
[00:31.000 --> 00:39.000] 録音とか録画とかをさせていただいているんですけれども、
[00:39.000 --> 00:44.000] 関係者だけ見るだけで、特に他に私もいないので、
[00:44.000 --> 00:47.000] あとは小児童弟もしっかりお話ししていただきますので、
[00:47.000 --> 00:48.000] お話しください。
[00:48.000 --> 00:49.000] はい。
[00:49.000 --> 00:51.000] はい。ではよろしくお願いします。
[00:51.000 --> 00:56.000] まず簡単に言うんですけど、名前とかお仕事とか、
[00:56.000 --> 01:01.000] ご家族とか、あと最近の趣味とか、
[01:01.000 --> 01:05.000] 最近の趣味とか、最近こんなこと気になっているとか、
[01:05.000 --> 01:07.000] こういうことやっているみたいなことがあれば、
[01:07.000 --> 01:10.000] 自己紹介みたいな感じで教えてもらってもいいですか?
[01:10.000 --> 01:11.000] はい。
[01:14.000 --> 01:15.000] 三村と言

In [18]:
segments = result['segments']
prog = re.compile('教えて|聞か|聞き|願い|ください|ですか|でしょうか|ましたか|されましたか|いつ頃')
INTERVIEW = []
for seg in segments:
  count = len(prog.findall(seg['text']))
  if count > 0: print(seg['text'])
  _seg = {'start': seg['start'], 'end': seg['end'], 'text': seg['text'], 'count': count}
  INTERVIEW.append(_seg)

よろしくお願いします。
お話しください。
はい。ではよろしくお願いします。
自己紹介みたいな感じで教えてもらってもいいですか?
三村さん、なんて呼ばれているんですか?
あれですか、趣味の美術とか音楽とかっていうのは、
何か、お話ししたいですか?
あれですか、趣味の美術とか音楽とかっていうのは、
ああ、そうですか。


In [19]:
segments = result['segments']
embedding_model = PretrainedSpeakerEmbedding("speechbrain/spkrec-ecapa-voxceleb", device='cpu')
embeddings = np.zeros(shape=(len(segments), 192))

duration = video.duration
embeddings = []


for i, segment in enumerate(segments):
    audio = Audio()
    start = segment["start"]
    end = min(duration, segment["end"])
    clip = Segment(start, end)
    waveform, sample_rate = audio.crop(audio_path, clip)
    print(waveform[0])
    _enbed = embedding_model(waveform[None])
    #print(_enbed[0])
    embeddings.append(_enbed[0])

embeddings = np.nan_to_num(embeddings)


tensor([0.0000, 0.0000, 0.0000,  ..., 0.0161, 0.0197, 0.0204])
tensor([ 0.0201,  0.0227,  0.0232,  ..., -0.0106, -0.0089, -0.0089])
tensor([-0.0083, -0.0067, -0.0080,  ..., -0.0044, -0.0043, -0.0045])
tensor([-0.0045, -0.0050, -0.0037,  ...,  0.0276,  0.0266,  0.0267])
tensor([0.0257, 0.0236, 0.0234,  ..., 0.0067, 0.0067, 0.0056])
tensor([ 0.0043,  0.0037,  0.0028,  ..., -0.0038, -0.0042, -0.0036])
tensor([-0.0029, -0.0033, -0.0036,  ...,  0.0210,  0.0222,  0.0218])
tensor([0.0204, 0.0196, 0.0173,  ..., 0.0068, 0.0057, 0.0050])
tensor([ 0.0049,  0.0049,  0.0050,  ..., -0.0031, -0.0013,  0.0009])
tensor([ 0.0016,  0.0030,  0.0046,  ..., -0.0113, -0.0113, -0.0105])
tensor([-1.0925e-02, -1.1383e-02, -1.0101e-02,  ..., -8.8501e-04,
         3.0518e-05, -1.0986e-03])
tensor([-0.0020, -0.0016, -0.0018,  ..., -0.0126, -0.0137, -0.0134])
tensor([-0.0151, -0.0158, -0.0153,  ..., -0.0014, -0.0011, -0.0017])
tensor([-0.0026, -0.0028, -0.0026,  ...,  0.0140,  0.0139,  0.0130])
tensor([0.0132, 0.01

In [20]:
from sklearn.cluster import AgglomerativeClustering
speaker_count = 2

In [22]:
clustering_agg = AgglomerativeClustering(speaker_count).fit(embeddings)

In [23]:
labeled_segments = []
for label, segment in zip(clustering_agg.labels_, result["segments"]):
    labeled_segments.append((label, segment["start"], segment["text"]))

interivew = []
print(INTERVIEW)
for s, (speaker, _, text) in enumerate(labeled_segments):
    stime = INTERVIEW[s]["start"]
    interivew.append(f"話者{speaker + 1} :  {stime} 〜 : 「{text}」")

[{'start': 0.0, 'end': 6.0, 'text': '今日はですね、ものを買われたり、サービスとか使われる時に、', 'count': 0}, {'start': 6.0, 'end': 9.0, 'text': 'どういうことを思っていらっしゃるとか、', 'count': 0}, {'start': 9.0, 'end': 12.0, 'text': 'そういう関係のことをお伺いしたいと思って、', 'count': 0}, {'start': 12.0, 'end': 14.0, 'text': '来ていただきました。', 'count': 0}, {'start': 14.0, 'end': 18.0, 'text': 'いろいろとお話を伺って、今後のサービスとか、', 'count': 0}, {'start': 18.0, 'end': 22.0, 'text': 'いろいろ考える時に、いかしてもらおうと思っておりますので、', 'count': 0}, {'start': 22.0, 'end': 25.0, 'text': '緩い感じでお話を伺えるようだと思いますので、', 'count': 0}, {'start': 25.0, 'end': 27.0, 'text': 'よろしくお願いします。', 'count': 1}, {'start': 27.0, 'end': 31.0, 'text': 'はい。あと一応今回のインタビューなんですけど、', 'count': 0}, {'start': 31.0, 'end': 39.0, 'text': '録音とか録画とかをさせていただいているんですけれども、', 'count': 0}, {'start': 39.0, 'end': 44.0, 'text': '関係者だけ見るだけで、特に他に私もいないので、', 'count': 0}, {'start': 44.0, 'end': 47.0, 'text': 'あとは小児童弟もしっかりお話ししていただきますので、', 'count': 0}, {'start': 47.0, 'end': 48.0, 'text': 'お話しください。', 'count': 1}, {'start': 48.0, 'end': 49.0, 'te

In [24]:
for speek in interivew:
  print(speek)

話者1 :  0.0 〜 : 「今日はですね、ものを買われたり、サービスとか使われる時に、」
話者1 :  6.0 〜 : 「どういうことを思っていらっしゃるとか、」
話者1 :  9.0 〜 : 「そういう関係のことをお伺いしたいと思って、」
話者1 :  12.0 〜 : 「来ていただきました。」
話者1 :  14.0 〜 : 「いろいろとお話を伺って、今後のサービスとか、」
話者1 :  18.0 〜 : 「いろいろ考える時に、いかしてもらおうと思っておりますので、」
話者1 :  22.0 〜 : 「緩い感じでお話を伺えるようだと思いますので、」
話者1 :  25.0 〜 : 「よろしくお願いします。」
話者1 :  27.0 〜 : 「はい。あと一応今回のインタビューなんですけど、」
話者1 :  31.0 〜 : 「録音とか録画とかをさせていただいているんですけれども、」
話者1 :  39.0 〜 : 「関係者だけ見るだけで、特に他に私もいないので、」
話者1 :  44.0 〜 : 「あとは小児童弟もしっかりお話ししていただきますので、」
話者1 :  47.0 〜 : 「お話しください。」
話者1 :  48.0 〜 : 「はい。」
話者1 :  49.0 〜 : 「はい。ではよろしくお願いします。」
話者1 :  51.0 〜 : 「まず簡単に言うんですけど、名前とかお仕事とか、」
話者1 :  56.0 〜 : 「ご家族とか、あと最近の趣味とか、」
話者1 :  61.0 〜 : 「最近の趣味とか、最近こんなこと気になっているとか、」
話者1 :  65.0 〜 : 「こういうことやっているみたいなことがあれば、」
話者1 :  67.0 〜 : 「自己紹介みたいな感じで教えてもらってもいいですか?」
話者1 :  70.0 〜 : 「はい。」
話者2 :  74.0 〜 : 「三村と言います。」
話者1 :  75.0 〜 : 「はい。」
話者2 :  79.0 〜 : 「仕事は、」
話者1 :  80.0 〜 : 「三村さん、なんて呼ばれているんですか?」
話者1 :  84.0 〜 : 「お友達には。」
話者1 :  85.0 〜 : 「あだ名とかあります?」
話者2 :  87.0 〜 : 「あだ名は、結構名前を文字って呼ばれるかも

In [ ]:
from sklearn import cluster
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
clustering_kmeans = cluster.KMeans(n_clusters=speaker_count)
clustering_kmeans.fit(embeddings)

KMeans(n_clusters=2)

In [ ]:
labeled_segments = []
for label, segment in zip(clustering_kmeans.labels_, result["segments"]):
    labeled_segments.append((label, segment["start"], segment["text"]))

interivew = []
print(INTERVIEW)
for s, (speaker, _, text) in enumerate(labeled_segments):
    stime = INTERVIEW[s]["start"]
    interivew.append(f"話者{speaker + 1} :  {stime} 〜 : 「{text}」")

[{'start': 0.0, 'end': 10.0, 'text': 'どうもこんにちは', 'count': 0}, {'start': 10.0, 'end': 12.0, 'text': 'ありがとうございます', 'count': 0}, {'start': 12.0, 'end': 19.0, 'text': 'ごめん 記者の時間いただきましてどうもありがとうございます', 'count': 0}, {'start': 20.0, 'end': 22.0, 'text': 'おはよう', 'count': 0}, {'start': 24.0, 'end': 29.0, 'text': 'では早速質問をさせていただきたいと思います', 'count': 0}, {'start': 29.0, 'end': 31.0, 'text': 'ちょっとだけお願いします', 'count': 1}, {'start': 31.0, 'end': 49.0, 'text': 'では早速なんですけれども', 'count': 0}, {'start': 49.0, 'end': 55.0, 'text': 'まずフリーをどうでしたでしょうか', 'count': 1}, {'start': 56.0, 'end': 62.0, 'text': '今ちょっと回線がフリーズして聞こえなかったんですけど', 'count': 0}, {'start': 62.0, 'end': 67.0, 'text': 'フリーを導入されたのはいつ頃でしたでしょうか', 'count': 2}, {'start': 67.0, 'end': 79.0, 'text': '今から6年前で2018年の4月ですね', 'count': 0}, {'start': 79.0, 'end': 83.0, 'text': 'すごい そんな前からだったんですね', 'count': 0}, {'start': 83.0, 'end': 85.0, 'text': 'はい', 'count': 0}, {'start': 85.0, 'end': 91.0, 'text': 'その当時他の例えばクラウド会計のものとかって', 'count': 0}, {'start': 91.0, 'end': 93

In [ ]:
for speek in interivew:
  print(speek)

話者2 :  0.0 〜 : 「どうもこんにちは」
話者2 :  10.0 〜 : 「ありがとうございます」
話者2 :  12.0 〜 : 「ごめん 記者の時間いただきましてどうもありがとうございます」
話者2 :  20.0 〜 : 「おはよう」
話者2 :  24.0 〜 : 「では早速質問をさせていただきたいと思います」
話者2 :  29.0 〜 : 「ちょっとだけお願いします」
話者2 :  31.0 〜 : 「では早速なんですけれども」
話者2 :  49.0 〜 : 「まずフリーをどうでしたでしょうか」
話者2 :  56.0 〜 : 「今ちょっと回線がフリーズして聞こえなかったんですけど」
話者2 :  62.0 〜 : 「フリーを導入されたのはいつ頃でしたでしょうか」
話者1 :  67.0 〜 : 「今から6年前で2018年の4月ですね」
話者2 :  79.0 〜 : 「すごい そんな前からだったんですね」
話者2 :  83.0 〜 : 「はい」
話者2 :  85.0 〜 : 「その当時他の例えばクラウド会計のものとかって」
話者2 :  91.0 〜 : 「検討されましたでしょうか」
話者1 :  93.0 〜 : 「マネーフォアードとフリーとどっちにしようかなという話はちょっと」
話者1 :  101.0 〜 : 「私の中だけでありましたけども」
話者1 :  105.0 〜 : 「フリーの方がどうも私はその会計に詳しい人間ではないので」
話者1 :  113.0 〜 : 「初心者向きだという話がちょっとしまったのレビューでありましたので」
話者2 :  123.0 〜 : 「じゃあフリーの方いいかなと思ってフリーにしました」
話者2 :  129.0 〜 : 「少し出しました」
話者2 :  131.0 〜 : 「価格とかはその時って検討されましたか企画というか」
話者1 :  138.0 〜 : 「あまり積極的に企画してないんですけど」
話者1 :  145.0 〜 : 「一応フリーの方は」
話者1 :  148.0 〜 : 「いくらだったかな」
話者1 :  150.0 〜 : 「1万2万弱という感じだったので」
話者2 :  156.0 〜 : 「それぐらいならいいかなと思ってそれにしました」
話者2 :  161.0 〜 :